### PR TITLE
Add Meta characters

### PR DESCRIPTION
**Pull request by Ogi22po**
I think this section should be mentioned in the syntax.
Please consider adding it.
Please edit it so that it is correct and fit and move in the right place.

### CODE REVIEW

**Comment by Ogi22po** [comment]
@googlebot I signed it!

**Comment by junyer** [comment]
Thank you for the suggestion. In general, I would prefer not to enumerate the metacharacters like that. The thing is that their special meanings are lost (or in a couple of cases, changed) within the context of a character class, but you will often see people escaping them inside character classes. Saying "these are the metacharacters" probably has a lot to do with that, I suspect, in that people end up misunderstanding the meaning of what they are writing. It doesn't hurt, arguably, but then using extra parentheses in arithmetic expressions doesn't hurt either and yet no one would argue that it's okay not to understand operator precedence. Does that make sense? :)

**Comment by Ogi22po** [comment]
Hello.
Thank you for your time
Nowhere in the RE2 syntax in GitHub have found an explanation of what role the given characters have and how their role changes case by case and how to intentionally cancel a given task.
I think it should be in syntax.
I had to learn from youtube tutorial.
Perhaps it would be good to ask:
- do these characters have a special function?
- does this feature change depending on the location of the character?
- is it possible to influence this function??
- is this listed in the syntax?
I think it is common practice in other languages to explain such an essential thing (html, css, xml, MathML, ...)

**Comment by junyer** [comment]
Although I'm extremely sympathetic to the view that learning/teaching regular expressions is hard and could/should be done better, the RE2 syntax documentation ultimately exists to specify which syntactic elements RE2 does and doesn't support. For an introduction to regular expressions, the [Perl regular expressions tutorial](https://perldoc.perl.org/perlretut.html) is likely one of the better resources currently and freely available.

**Pull request closed without merging**
