### PR TITLE
Restrict using slim locks on Windows to supporting versions

### LINKED ISSUE #247: New Slim Locks usage broken on older versions of Windows and default MinGW
https://github.com/google/re2/commit/bc40cdeb40ad56327da31ae3d8f3983994d9c616 added in using Windows slim locks in mutexes for a performance gain.
Unfortunately these locks are not available in older (pre-Vista) versions of the Windows API. This causes issues for cross compiling using MinGW, which defaults to an older API.

I will post a PR to correct this.

### PR DESCRIPTION
**Pull request by zoddicus**
Fixes #247

### CODE REVIEW

**Comment by zoddicus** [comment]
@Donis- @junyer PTAL

**Comment by junyer** [comment]
Thanks for the patch! We use Gerrit, not pull requests, so I will go ahead and land this that way.

**Comment by zoddicus** [comment]
Thanks, I will keep that in mind if I have to submit future changes.

**Comment by Donis-** [comment]
Sounds good!

**Pull request closed without merging**
